[package]
name = "polycalc"
version = "0.1.0"
authors = ["Legorooj <legorooj@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"

[profile.dev]
opt-level = 3
lto = "fat"
